### PR TITLE
fix bugs

### LINKED ISSUE #198: 使用记录的筛选条件那里有错误
选择了当天00.00 到 03.07的记录，但是没有显示任何记录。

Image
如果选择昨天的或者前几天都可以，当天的就没有。

### LINKED ISSUE #201: [bug] group not saved
Provider group name and user group not saved. Checked. both.

Image

### LINKED ISSUE #204: 供应商管理的统计和使用记录有出入
猜测是重试的时候依旧算在了第一次请求失败的供应商头上

Image

Image

### PR DESCRIPTION
**Pull request by ding113**
## Summary
This PR fixes multiple bugs and consolidates database migrations into a single idempotent migration file.

## Problem
- **#204**: Provider statistics showed discrepancies with usage records (retry requests were counted against the wrong provider)
- **#201**: Provider group name and user group settings were not being saved properly
- **#198**: Usage records filter failed to show today's records due to date filtering issues

Additionally, the migration files (0020-0025) had conflicts causing upgrade issues for users on different versions.

## Solution
- Consolidated migrations 0020-0025 into a single idempotent migration (`0020_glossy_grandmaster.sql`)
- The new migration safely handles all upgrade paths:
  - Fresh installations
  - Upgrades from version 0019
  - Upgrades from conflicting migration versions
- Uses `IF NOT EXISTS` and exception handling for idempotent operations
- Cleans up conflicting migration records automatically

## Changes
- **Removed**: 7 conflicting migration files (0020-0024 variants)
- **Added**: Single consolidated migration `0020_glossy_grandmaster.sql` that:
  - Creates `daily_reset_mode` enum type (idempotent)
  - Updates provider timeout defaults to 0 (no limit)
  - Adds daily cost limit fields to keys and providers tables
  - Adds MCP passthrough fields to providers table
  - Adds billing model source to system_settings
  - Adds extended user limits (5h, weekly, monthly, concurrent sessions)
- **Updated**: Migration snapshot to reflect consolidated schema state

## Testing
- [ ] Tested fresh database installation
- [ ] Tested upgrade from version 0019
- [ ] Tested upgrade from conflicting migration versions
- [ ] Verified provider statistics accuracy
- [ ] Verified group settings persistence
- [ ] Verified date filtering for usage records

## Related Issues
Closes #204
Closes #201
Closes #198

### CODE REVIEW

**Comment by ding113** [comment]
## 📊 PR Size Analysis

This PR is **XL** with **5,568 lines** changed across **51 files**.

⚠️ Large PRs are harder to review and more likely to introduce bugs.

### 📋 Analysis Breakdown

**Migration Files (bulk of deletions):**
- ~4,500 lines are from migration file consolidation
- 7 old migration files deleted, 1 consolidated migration added
- This is cleanup work, low review risk

**Actual Feature/Bug Fix Changes (~39 files):**
1. **Usage logs filtering bug** (#198) - `usage-logs-*.tsx`, `usage-logs.ts`
2. **Group not saved bug** (#201) - `tag-input.tsx`, transformers, validation
3. **Provider stats mismatch** (#204) - `forwarder.ts`, `session.ts`, `message.ts`
4. **i18n updates** - 10 message JSON files

### 🔀 Suggested Split

Based on the changes, this PR could be split into:

1. **PR 1: Migration Consolidation**
   - `drizzle/0020_*.sql`, `drizzle/meta/*.json`
   - Low risk, database maintenance

2. **PR 2: Fix usage logs filtering (#198)**
   - `src/repository/usage-logs.ts`
   - `src/app/[locale]/dashboard/logs/_components/*`
   - Related i18n files

3. **PR 3: Fix group not saved (#201)**
   - `src/components/ui/tag-input.tsx`
   - `src/repository/_shared/transformers.ts`
   - `src/lib/validation/schemas.ts`

4. **PR 4: Fix provider stats mismatch (#204)**
   - `src/app/v1/_lib/proxy/forwarder.ts`
   - `src/app/v1/_lib/proxy/session.ts`
   - `src/repository/message.ts`

### Why Split?
- Easier to review each bug fix independently
- Faster CI feedback per change
- Easier to revert specific fixes if needed
- Better git history for tracking which fix addressed which issue

---
🤖 *Automated analysis by Claude AI*

**Comment by ding113** [comment]
## 🔒 Security Scan Results

✅ **No security vulnerabilities detected**

This PR has been scanned against OWASP Top 10, CWE Top 25, and common security anti-patterns. No security issues were identified in the code changes.

### 📋 Detailed Analysis

#### Changes Reviewed
- **Database migrations** (`drizzle/0020_glossy_grandmaster.sql`): Idempotent migration consolidating schema changes
- **Repository layer** (`src/repository/*.ts`): Updates to provider statistics, usage logs, system config
- **Proxy layer** (`src/app/v1/_lib/proxy/*.ts`): Model redirector, response handler, session management
- **UI components** (`src/app/[locale]/**/*.tsx`): Error details dialog, model display, tag input, settings form
- **Type definitions** (`src/types/system-config.ts`): New `BillingModelSource` type
- **Validation schemas** (`src/lib/validation/schemas.ts`): Schema updates for new settings

### Scanned Categories

| Category | Status | Notes |
|----------|--------|-------|
| **A01: Injection (SQL/NoSQL/Command)** | ✅ Clean | All SQL uses parameterized queries via Drizzle ORM `sql` template literals. The `timezone` variable comes from validated environment config (`TZ` with Zod schema). Time strings use `normalizeLocalTimeStr()` which only performs safe string manipulation. |
| **A02: Broken Authentication** | ✅ Clean | No authentication changes in this PR. |
| **A03: Sensitive Data Exposure** | ✅ Clean | No new logging of sensitive data. No hardcoded secrets. |
| **A04: XML External Entities (XXE)** | ✅ N/A | No XML parsing in changed code. |
| **A05: Broken Access Control** | ✅ Clean | No changes to authorization logic. Provider ID updates properly track the actual handling provider. |
| **A06: Security Misconfiguration** | ✅ Clean | Default values are appropriate. No debug mode enabled. |
| **A07: Cross-Site Scripting (XSS)** | ✅ Clean | React components use standard patterns. No `dangerouslySetInnerHTML`. User inputs in UI go through proper React escaping. |
| **A08: Insecure Deserialization** | ✅ Clean | JSON parsing only on trusted internal data (provider chain). |
| **A09: Known Vulnerabilities** | ✅ Clean | No new dependencies added. |
| **A10: Logging & Monitoring** | ✅ Clean | Proper logging maintained for debugging. |
| **SSRF** | ✅ Clean | No user-controlled URL fetching in changes. |
| **Path Traversal** | ✅ Clean | No file path operations with user input. |

### 🔍 Specific Findings Analysis

#### SQL Query Construction (src/repository/usage-logs.ts, src/repository/provider.ts)
- **Pattern**: Time filtering uses `startDateLocal`/`endDateLocal` strings directly in SQL
- **Assessment**: **SAFE** - The code uses Drizzle ORM's `sql` template literals which properly parameterize values:
  ```typescript
  sql`..AT TIME ZONE ${timezone}..>= ${localTimeStr}::timestamp`
  ```
  These are **parameterized queries**, not string concatenation. Values are escaped by Drizzle.

#### Timezone Variable (Environment Config)
- **Pattern**: `const timezone = getEnvConfig().TZ`
- **Assessment**: **SAFE** - The `TZ` variable comes from environment config validated by Zod schema with a safe default (`Asia/Shanghai`). Not user-controllable.

#### Time String Normalization (src/repository/usage-logs.ts)
- **Pattern**: `normalizeLocalTimeStr()` function
- **Assessment**: **SAFE** - Only performs string operations (`.replace("T", " ")`) on datetime-local format strings. No injection risk.

#### React Components (UI changes)
- **Pattern**: New props like `onRedirectClick`, `scrollToRedirect`, external dialog controls
- **Assessment**: **SAFE** - Standard React event handling patterns. No direct DOM manipulation with user data.

### 🛡️ Security Posture

**Strong** - This PR follows secure coding practices:
- Uses parameterized queries consistently
- Validates configuration with Zod schemas
- Proper React patterns for UI components
- No introduction of user-controllable data in sensitive operations

---
🤖 *Automated security scan by Claude AI - OWASP Top 10 & CWE coverage*

**Review by ding113 — COMMENTED** [review]
## ⚠️ Critical Bug Identified

**File:** `src/repository/provider.ts`

The SQL query uses `(mr.provider_chain->-1->>'providerId')::int` to extract the provider ID from the chain, but the `ProviderChainItem` interface (in `src/types/message.ts`) defines the field as `id`, NOT `providerId`:

```typescript
export interface ProviderChainItem {
  id: number;      // <-- The actual field name
  name: string;
  // ...
}
```

**Impact:** The SQL condition `(mr.provider_chain->-1->>'providerId')::int = p.id` will **always fail** because `providerId` doesn't exist in the JSON structure. This means:
- Provider statistics will only count requests where `provider_chain` is NULL or empty
- All requests with retry/failover chains will be excluded from statistics
- The `latest_call` CTE will produce incorrect results

**Suggested fix:**
Replace all occurrences of `->>'providerId'` with `->>'id'`:
```sql
-- Change from:
(mr.provider_chain->-1->>'providerId')::int = p.id

-- To:
(mr.provider_chain->-1->>'id')::int = p.id
```

This should be fixed in the following lines of `src/repository/provider.ts`:
- Line 380
- Line 383
- Line 392
- Line 395
- Line 401

**Comment by ding113** [comment]
## 📊 PR Size Analysis

This PR is **XL** with **5,572 lines** changed (574 additions, 4,998 deletions) across **51 files**.

Large PRs are harder to review and more likely to introduce bugs.

### 📝 Analysis Notes

Looking at the changes, I notice that a significant portion of the deletions (~4,500+ lines) come from:
- Removing 7 conflicting migration files
- Removing snapshot JSON files

The actual feature/fix changes appear smaller, but the PR still bundles multiple distinct concerns.

### 🔀 Suggested Split

Based on the changes, this PR could be split into:

1. **PR 1: Migration Consolidation** - Consolidate migrations 0020-0025
   - `drizzle/0020_glossy_grandmaster.sql` (new consolidated migration)
   - `drizzle/0020_next_juggernaut.sql` (delete)
   - `drizzle/0021_daily_cost_limits.sql` (delete)
   - `drizzle/0023_*.sql` files (delete)
   - `drizzle/0024_*.sql` (delete)
   - `drizzle/meta/*.json` snapshot updates
   - `src/lib/migrate.ts`

2. **PR 2: Provider Statistics Fix (#204)**
   - `src/app/v1/_lib/proxy/forwarder.ts`
   - `src/app/v1/_lib/proxy/session.ts`
   - `src/repository/message.ts`
   - Related test files

3. **PR 3: Group Settings Persistence Fix (#201)**
   - `src/actions/system-config.ts`
   - `src/repository/system-config.ts`
   - `src/types/system-config.ts`
   - Settings form components

4. **PR 4: Usage Logs Date Filter Fix (#198)**
   - `src/app/[locale]/dashboard/logs/_components/` files
   - `src/repository/usage-logs.ts`
   - Related i18n message updates

### Why Split?
- Easier to review each fix independently
- Faster CI feedback per change
- Easier to revert specific fixes if needed
- Better git history for debugging
- Migration changes can be merged first to unblock users with upgrade issues

### Alternative Approach

If splitting is not practical, at minimum consider:
- Separating the migration consolidation (PR 1) from the bug fixes
- This would allow the migration fix to be released quickly to help users with upgrade issues

---
🤖 *Automated analysis by Claude AI*

**Comment by ding113** [comment]
## 🔒 Security Scan Results

✅ **No security vulnerabilities detected**

This PR has been scanned against OWASP Top 10, CWE Top 25, and common security anti-patterns. No security issues were identified in the code changes.

### Changes Analyzed

This PR adds comprehensive usage logs functionality with the following security-relevant components:

1. **Database Queries** (`src/repository/usage-logs.ts`):
   - ✅ Uses Drizzle ORM with parameterized queries - no SQL injection risk
   - ✅ User inputs (filters) are properly bound using `eq()`, `sql` template literals with parameter interpolation
   - ✅ Timezone value comes from server-side `getEnvConfig().TZ`, not user input

2. **Access Control** (`src/actions/usage-logs.ts`):
   - ✅ All endpoints require authentication via `getSession()`
   - ✅ Non-admin users are restricted to their own data (`userId: session.user.id`)
   - ✅ Admin role check before allowing broader access

3. **Input Validation** (`src/lib/validation/schemas.ts`):
   - ✅ Zod schemas with appropriate constraints (min/max values, enums)
   - ✅ Integer validation for retention days and batch sizes
   - ✅ Boolean validation for feature flags

4. **Provider Statistics** (`src/repository/provider.ts`):
   - ✅ Uses raw SQL but timezone comes from server config, not user input
   - ✅ No user-controllable data in SQL queries

5. **UI Components** (`src/components/usage-logs/`):
   - ✅ React components with proper data binding (no `dangerouslySetInnerHTML`)
   - ✅ Data displayed through React's automatic XSS protection

### Scanned Categories

- ✅ **Injection attacks** (SQL, NoSQL, Command, LDAP) - Clean: Uses parameterized queries via Drizzle ORM
- ✅ **Authentication and session management** - Clean: Session validation on all endpoints
- ✅ **Sensitive data exposure** - Clean: No credentials or secrets in code
- ✅ **Access control and authorization** - Clean: Role-based access with user filtering
- ✅ **Security misconfiguration** - Clean: No debug code or exposed secrets
- ✅ **Cross-site scripting (XSS)** - Clean: React auto-escaping, no unsafe HTML rendering
- ✅ **Insecure deserialization** - Clean: Zod schema validation on inputs
- ✅ **SSRF and path traversal** - N/A: No URL fetching or file operations
- ✅ **Cryptographic weaknesses** - N/A: No cryptographic operations in changes

### OWASP Top 10 Coverage

- [x] A01: Injection - Clean (parameterized queries)
- [x] A02: Broken Authentication - Clean (session validation)
- [x] A03: Sensitive Data Exposure - Clean
- [ ] A04: XML External Entities - N/A (no XML parsing)
- [x] A05: Broken Access Control - Clean (role-based filtering)
- [x] A06: Security Misconfiguration - Clean
- [x] A07: XSS - Clean (React escaping)
- [ ] A08: Insecure Deserialization - N/A (Zod validation)
- [ ] A09: Known Vulnerabilities - Not scoped
- [x] A10: Logging & Monitoring - Clean (error logging present)

### 🛡️ Security Posture

**Strong** - The codebase follows security best practices:
- Uses ORM with parameterized queries
- Implements proper authentication and authorization
- Validates inputs with Zod schemas
- Server-side configuration for sensitive values

---
🤖 *Automated security scan by Claude AI - OWASP Top 10 & CWE coverage*

File: drizzle/0020_glossy_grandmaster.sql [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+-- Step 4: 添加 providers 表字段（幂等）
+ALTER TABLE "providers" ADD COLUMN IF NOT EXISTS "mcp_passthrough_type" varchar(20) DEFAULT 'none' NOT NULL;--> statement-breakpoint
+ALTER TABLE "providers" ADD COLUMN IF NOT EXISTS "mcp_passthrough_url" varchar(512);--> statement-breakpoint
+ALTER TABLE "providers" ADD COLUMN IF NOT EXISTS "daily_reset_mode" "daily_reset_mode" DEFAULT 'fixed' NOT NULL;--> statement-breakpoint
+ALTER TABLE "providers" ADD COLUMN IF NOT EXISTS "limit_daily_usd" numeric(10, 2);--> statement-breakpoint
+ALTER TABLE "providers" ADD COLUMN IF NOT EXISTS "daily_reset_time" varchar(5) DEFAULT '00:00' NOT NULL;--> statement-breakpoint
+
+-- Step 5: 添加 system_settings 表字段（幂等）
+ALTER TABLE "system_settings" ADD COLUMN IF NOT EXISTS "billing_model_source" varchar(20) DEFAULT 'original' NOT NULL;--> statement-breakpoint
+
```
Comment (ding113) [inline drizzle/0020_glossy_grandmaster.sql:43]: 🔴 **Critical**: Missing `billing_model_source` column in migration

**Why this is a problem**: The schema at `src/drizzle/schema.ts` adds `billingModelSource` column to `system_settings` table, and the repository code (`src/repository/system-config.ts`) queries this field. However, this migration file does not add this column. This will cause database errors for users running this migration:
- `SELECT ... billing_model_source ...` will fail with "column does not exist"
- `INSERT` statements including this field will fail

**Suggested fix**: Add this line after Step 5 in the migration:
```sql
-- Step 5.1: 添加 system_settings 计费模型来源字段（幂等）
ALTER TABLE "system_settings" ADD COLUMN IF NOT EXISTS "billing_model_source" varchar(20) DEFAULT 'original' NOT NULL;--> statement-breakpoint
```

**Review by ding113 — COMMENTED** [review]
## 📋 Code Review Summary

This PR consolidates database migrations (0020-0025) into a single idempotent migration file and adds billing model source configuration feature. The migration consolidation approach is sound.

## 🔍 Issues Found

- **Critical (🔴)**: 1 issue
- **High (🟠)**: 0 issues  
- **Medium (🟡)**: 0 issues
- **Low (🟢)**: 1 issue

## 🎯 Priority Actions

1. **Critical**: The migration file `0020_glossy_grandmaster.sql` is missing the `billing_model_source` column addition for `system_settings` table, but the code (schema.ts, repository files, types) expects this column to exist. This will cause runtime errors.

## 💡 General Observations

The migration consolidation strategy is well-designed with proper idempotent operations using `IF NOT EXISTS`. However, the new `billing_model_source` feature added in this PR requires a corresponding migration entry that is currently missing.

---
🤖 *Automated review by Claude AI - focused on identifying issues for improvement*

File: src/repository/usage-logs.ts [hunk 2]
```diff
@@ -65,13 +67,27 @@ export interface UsageLogsResult {
 /**
  * 查询使用日志（支持多种筛选条件和分页）
  */
+/**
+ * 将本地时间字符串标准化为 "YYYY-MM-DD HH:mm:ss" 格式
+ * 支持输入格式: "YYYY-MM-DDTHH:mm" 或 "YYYY-MM-DD HH:mm:ss"
+ */
+function normalizeLocalTimeStr(input: string): string {
+  // 处理 datetime-local 格式: "2025-11-26T00:00" → "2025-11-26 00:00:00"
```
Comment (ding113) [inline src/repository/usage-logs.ts:75]: 🟢 **Low**: Missing input validation in `normalizeLocalTimeStr` function

**Why this is a problem**: The function assumes the input string is always in a valid format (`YYYY-MM-DDTHH:mm` or `YYYY-MM-DD HH:mm:ss`). If an unexpected format is passed (e.g., malformed string, empty string, or different format), it will silently produce incorrect results instead of failing early. This could lead to incorrect SQL queries.

**Suggested fix**:
```typescript
function normalizeLocalTimeStr(input: string): string {
  // Validate input format
  if (!input || typeof input !== "string") {
    throw new Error("Invalid time string: input is empty or not a string");
  }
  
  // Validate expected formats: "YYYY-MM-DDTHH:mm" (16 chars) or "YYYY-MM-DD HH:mm:ss" (19 chars)
  const trimmed = input.trim();
  if (trimmed.length < 16) {
    throw new Error(`Invalid time string format: ${input}`);
  }
  
  // 处理 datetime-local 格式: "2025-11-26T00:00" → "2025-11-26 00:00:00"
  const normalized = trimmed.replace("T", " ");
  // 如果没有秒数，补充 ":00"
  if (normalized.length === 16) {
    return normalized + ":00";
  }
  return normalized;
}
```

**Review by ding113 — COMMENTED** [review]
## 📋 Code Review Summary (Updated)

This PR adds a new "billing model source" configuration feature that allows administrators to control whether billing uses the original model (before redirection) or the redirected model (after redirection). It also consolidates database migrations, improves time zone handling for log filters, and fixes UI/UX issues.

## 🔍 Issues Found

- **Critical (🔴)**: 0 issues
- **High (🟠)**: 0 issues  
- **Medium (🟡)**: 0 issues
- **Low (🟢)**: 1 issue

## 🎯 Priority Actions

1. **Low**: Consider adding input validation to `normalizeLocalTimeStr` function in `src/repository/usage-logs.ts` to handle edge cases gracefully

## 💡 General Observations

**Well-implemented features:**
- The billing model source feature is properly integrated across the stack (schema, repository, actions, UI)
- Migration consolidation is well-designed with idempotent operations
- Time zone handling refactoring from `Date` objects to local time strings avoids serialization issues
- The model redirector reset logic handles provider switching correctly
- CountUp animation fix using `useRef` prevents stale closure issues
- TagInput `onBlur` handler improves UX by committing pending values

**Code Quality:**
- Consistent use of TypeScript types (`BillingModelSource` type)
- Proper i18n support across all 5 languages
- UI accessibility improvements with scroll-to-section functionality

---
🤖 *Automated review by Claude AI - focused on identifying issues for improvement*

**Review by ding113 — COMMENTED** [review]
## 📋 Code Review Summary (Updated)

This PR adds a new "billing model source" configuration feature that allows administrators to control whether billing uses the original model (before redirection) or the redirected model (after redirection). It also consolidates database migrations, improves time zone handling for log filters, and fixes UI/UX issues.

## 🔍 Issues Found

- **Critical (🔴)**: 0 issues
- **High (🟠)**: 0 issues  
- **Medium (🟡)**: 0 issues
- **Low (🟢)**: 1 issue

## 🎯 Priority Actions

1. **Low**: Consider adding input validation to `normalizeLocalTimeStr` function in `src/repository/usage-logs.ts` to handle edge cases gracefully

## 💡 General Observations

**Well-implemented features:**
- The billing model source feature is properly integrated across the stack (schema, repository, actions, UI)
- Migration consolidation is well-designed with idempotent operations
- Time zone handling refactoring from `Date` objects to local time strings avoids serialization issues
- The model redirector reset logic handles provider switching correctly
- CountUp animation fix using `useRef` prevents stale closure issues
- TagInput `onBlur` handler improves UX by committing pending values

**Code Quality:**
- Consistent use of TypeScript types (`BillingModelSource` type)
- Proper i18n support across all 5 languages
- UI accessibility improvements with scroll-to-section functionality

---
🤖 *Automated review by Claude AI - focused on identifying issues for improvement*
